# Generated by Django 3.1.7 on 2021-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=256)),
                ('category', models.CharField(db_index=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('data', models.JSONField(help_text='JSON data')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Event occurred timestamp')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('session_id', 'timestamp'), name='unique event for session'),
        ),
    ]
